version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing AWS CLI and unzip tools...
      - apt-get update && apt-get install -y unzip

  pre_build:
    commands:
      - echo Logging in as AWS CLI user...
      - aws sts get-caller-identity
      - echo Preparing to deploy Lambda functions...

  build:
    commands:
      - echo Deploying lambda function: search-opensearch
      - aws lambda update-function-code --function-name search-opensearch --zip-file fileb://search-opensearch.zip
      - echo Deploying lambda function: upload-to-search
      - aws lambda update-function-code --function-name upload-to-search --zip-file fileb://upload-to-search.zip
      - echo Deploying lambda function: searchFunction
      - aws lambda update-function-code --function-name searchFunction --zip-file fileb://searchFunction.zip
      - echo Deploying lambda function: lambda-pdftotxt
      - aws lambda update-function-code --function-name lambda-pdftotxt --zip-file fileb://lambda-pdftotxt.zip

artifacts:
  files:
    - '**/*'

